export const types = {
    SHOW_TOAST: "SHOW_TOAST",
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    SHOW_SIDEBAR_LOADER: "SHOW_SIDEBAR_LOADER",
    HIDE_SIDEBAR_LOADER: "HIDE_SIDEBAR_LOADER",
    USER_DETAIL: "USER_DETAIL",

    //Employee
    ALL_EMPLOYEES: "ALL_EMPLOYEES",
    CHANGE_EMPLOYEE_DATA: "CHANGE_EMPLOYEE_DATA",
    //Permissions
    CHANGE_PERMISSIONS: "CHANGE_PERMISSIONS",
    //Operations
    CHANGE_OPERATIONS: "CHANGE_OPERATIONS",
    //machines
    CHANGE_MACHINES: "CHANGE_MACHINES",
    //Tools
    CHANGE_TOOLS: "CHANGE_TOOLS",
    //Projects
    CHANGE_PROJECTS: "CHANGE_PROJECTS",
    CHANGE_READY_PROJECTS: "CHANGE_READY_PROJECTS",
    GET_OPERATIONS_TREE: "GET_OPERATIONS_TREE",

    //Replacement
    CHANGE_REPLACEMENTS: "CHANGE_REPLACEMENTS",

    //Category
    CHANGE_CATEGORY: "CHANGE_CATEGORY",

    //Material
    CHANGE_MATERIALS: "CHANGE_MATERIALS",
    ADD_MATERIALS: "ADD_MATERIALS",
    EDIT_MATERIALS: "EDIT_MATERIALS",
    ADD_MATERIALS_ID: "ADD_MATERIALS_ID",
    //Supplier

    CHANGE_SUPPLIERS: "CHANGE_SUPPLIERS",

    //Misc
    CHANGE_TAG_DATA: "CHANGE_TAG_DATA",
    CHANGE_UNIT_DATA: "CHANGE_UNIT_DATA",
    CHANGE_INJECTION_TYPE_DATA: "CHANGE_INJECTION_TYPE_DATA",
    CHANGE_GROUP_DATA: "CHANGE_GROUP_DATA",
    CHANGE_SEASON_DATA: "CHANGE_SEASON_DATA",
    CHANGE_TOOL_TYPE_DATA: "CHANGE_TOOL_TYPE_DATA",
    CHANGE_CLASS_TYPE_DATA: "CHANGE_CLASS_TYPE_DATA",
    //Customers
    CHANGE_CUSTOMERS: "CHANGE_CUSTOMERS",

    //Sales
    CHANGE_DRAFTS: "CHANGE_DRAFTS",
    CHANGE_ORDERS: "CHANGE_ORDERS",
};
